### ISSUE TITLE
Latest version of TestNG (7.1.0) doesn't work with Allure

### ISSUE THREAD

**Issue by vkhromenkov** [allure-framework/allure-java#415]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Getting java.lang.NoClassDefFoundError: org/testng/IInvokedMethodListener2 on running any test

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Any simple project with latest Allure and TestNG will be broken

#### What is the expected behavior?
Successfull test runs

#### What is the motivation / use case for changing the behavior?
org.testng.IInvokedMethodListener2 used by allure-testng was deprecated in TestNG 7.1

#### Please tell us about your environment:

| Allure version | 2.13.1 |
| --- | --- |
| Test framework | testng@7.1.0 |
| Allure integration | allure-testng@2.13.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by Krab1** [comment]
got same issue i guess it is in the class AllureTestNg just replace IInvokedMethodListener2 to IInvokedMethodListener should be ok

**Comment by ttiernan** [comment]
We are facing the exact same issue during our test executions with TestNG v7.1.0 and Allure TestNG/Java v2.13.1:

   java.lang.NoClassDefFoundError: org/testng/IInvokedMethodListener

**Comment by dr29bart** [comment]
It looks like it is fixed by https://github.com/allure-framework/allure-java/pull/422

**Comment by anca1108** [comment]
I still have the same issue. is it working for everyone else?

**Comment by mrbaco** [comment]
I have the same issue with TestNG 7.1.0 and Allure 2.8.1. It seems this wasn't fixed.

**Comment by iNTEAM** [comment]
> I still have the same issue. is it working for everyone else?

Still not working

**Comment by jesus-ramos-wag** [comment]
For those using the Gradle plugin and are still having this issue, what fixed it for me was making sure the **allureJavaVersion** in build.gradle was set to the latest version:

```
allure {
    version = '2.13.2'
    autoconfigure = true
    aspectjweaver = true
    allureJavaVersion = '2.13.2'
}
```

**Comment by clyde-dsouza** [comment]
For me updating the 'allure-testng' version to '2.14.0' fixed the issue
       <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>2.14.0</version>
        </dependency>
